server:
  port: 8081

spring:
  applications:
    name: UAT PROFILE

  datasource:
    url: jdbc:postgresql://192.168.58.187:5432/mydb
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.training.test: DEBUG
